FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm ci --fetch-retries=5 --fetch-retry-mintimeout=20000 --fetch-retry-maxtimeout=120000 --fetch-timeout=300000

COPY . .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
