FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm ci --fetch-retries=5 --fetch-retry-mintimeout=20000 --fetch-retry-maxtimeout=120000 --fetch-timeout=300000

COPY . .
RUN npx prisma generate

CMD ["sh", "-c", "npx prisma generate && npm run start:dev"]
