import { CosmeticSlot, PrismaClient } from '@prisma/client';

export const defaultCosmetics = [
  {
    code: 'party_hat',
    name: 'Party Hat',
    slot: CosmeticSlot.HAT,
    cost: 50,
    iconKey: 'hat_party',
    isActive: true,
  },
  {
    code: 'medal',
    name: 'Medal',
    slot: CosmeticSlot.ACCESSORY,
    cost: 50,
    iconKey: 'acc_medal',
    isActive: true,
  },
  {
    code: 'cross_body_bag',
    name: 'Cross Body Bag',
    slot: CosmeticSlot.ACCESSORY,
    cost: 75,
    iconKey: 'acc_cbb',
    isActive: true,
  },
  {
    code: 'bucket_hat',
    name: 'Bucket Hat',
    slot: CosmeticSlot.HAT,
    cost: 75,
    iconKey: 'hat_bucket',
    isActive: true,
  },
  {
    code: 'sunglasses',
    name: 'Sunglasses',
    slot: CosmeticSlot.HAT,
    cost: 75,
    iconKey: 'hat_sunglasses',
    isActive: true,
  },
  {
    code: 'crown',
    name: 'Crown',
    slot: CosmeticSlot.HAT,
    cost: 150,
    iconKey: 'hat_crown',
    isActive: true,
  },
  {
    code: 'hoodie',
    name: 'Hoodie',
    slot: CosmeticSlot.ACCESSORY,
    cost: 150,
    iconKey: 'acc_hoodie',
    isActive: true,
  },
  {
    code: 'ribbon',
    name: 'Ribbon',
    slot: CosmeticSlot.ACCESSORY,
    cost: 30,
    iconKey: 'acc_ribbon',
    isActive: true,
  },
  {
    code: 'tie',
    name: 'Tie',
    slot: CosmeticSlot.ACCESSORY,
    cost: 50,
    iconKey: 'acc_tie',
    isActive: true,
  },
  {
    code: 'scarf',
    name: 'Scarf',
    slot: CosmeticSlot.ACCESSORY,
    cost: 60,
    iconKey: 'acc_scarf',
    isActive: true,
  },
  {
    code: 'sweat_band',
    name: 'Sweat Band',
    slot: CosmeticSlot.HAT,
    cost: 60,
    iconKey: 'hat_sweat_band',
    isActive: true,
  },
  {
    code: 'bunny_ears',
    name: 'Bunny Ears',
    slot: CosmeticSlot.HAT,
    cost: 75,
    iconKey: 'hat_bunny_ears',
    isActive: true,
  },
  {
    code: 'frog_hat',
    name: 'Frog Hat',
    slot: CosmeticSlot.HAT,
    cost: 75,
    iconKey: 'hat_frog',
    isActive: true,
  },
  {
    code: 'overalls',
    name: 'Overalls',
    slot: CosmeticSlot.ACCESSORY,
    cost: 90,
    iconKey: 'acc_overalls',
    isActive: true,
  },
  {
    code: 'tutu',
    name: 'Tutu',
    slot: CosmeticSlot.ACCESSORY,
    cost: 90,
    iconKey: 'acc_tutu',
    isActive: true,
  },
  {
    code: 'viking_helmet',
    name: 'Viking Helmet',
    slot: CosmeticSlot.HAT,
    cost: 100,
    iconKey: 'hat_viking_helmet',
    isActive: true,
  },
  {
    code: 'varsity_jacket',
    name: 'Varsity Jacket',
    slot: CosmeticSlot.ACCESSORY,
    cost: 110,
    iconKey: 'acc_varsity_jacket',
    isActive: true,
  },
  {
    code: 'halo',
    name: 'Halo',
    slot: CosmeticSlot.HAT,
    cost: 125,
    iconKey: 'hat_halo',
    isActive: true,
  },
  {
    code: 'angel_wings',
    name: 'Angel Wings',
    slot: CosmeticSlot.ACCESSORY,
    cost: 150,
    iconKey: 'acc_angel_wings',
    isActive: true,
  },
  {
    code: 'astronaut_helmet',
    name: 'Astronaut Helmet',
    slot: CosmeticSlot.HAT,
    cost: 150,
    iconKey: 'hat_astronaut_helmet',
    isActive: true,
  },
];

export async function seedCosmetics(prisma: PrismaClient) {
  for (const item of defaultCosmetics) {
    await prisma.cosmeticItem.upsert({
      where: { code: item.code },
      update: item,
      create: item,
    });
  }
}
